version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=5000
      - MONGODB_URI=<YOUR_MONGODB_URI>
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
